export function createLegacyState(createDefaultProfile) {
  return {
    activeProfileId: null,
    selectedProfileObjectType: "static-route",
    lastReport: null,
    initialConfigSnapshot: null,
    syncingEditorScroll: false,
    syncingDiffScroll: false,
    connectorFrame: null,
    semanticObjectAlignFrame: null,
    semanticObjectWidthFrame: null,
    draggingProfileLine: null,
    selectedProfileLineLink: null,
    pendingProfileLineRef: null,
    lastProfileExampleSource: "",
    selectedProfileLibraryId: null,
    compareDirty: false,
    profileChanges: [],
    profileSavedSnapshot: null,
    profileUndoStack: [],
    selectedSemanticTokens: { old: [], new: [] },
    activeSemanticSelectionSource: "",
    draggingProfileToken: null,
    suppressNextPreviewTokenClick: false,
    pendingSemanticMapping: null,
    activeDiffObjectKey: "",
    activeSemanticPairKey: "",
    activeLineRelationKey: "",
    compareLoading: false,
    diffRenderVersion: 0,
    lastSemanticSummary: null,
    lastSemanticPlan: [],
    lastManualMap: {},
    lastDashboardData: null,
    lastCoverageDiagnostics: null,
    lastStandardsAudit: null,
    lastStandardsAuditRaw: null,
    lastAnalysisContext: null,
    exceptionTargets: new Map(),
    summaryIssueGroups: new Map(),
    activeIssueContext: null,
    lastSessionName: "",
    semanticPairKeyboardBound: false,
    lineRelationDelegationBound: false,
    connectorSvgDelegationBound: false,
    diffResizeObserver: null,
    diffMutationObserver: null,
    connectorSettleTimer: null,
    diffScrollPositions: {
      old: { top: 0, left: 0 },
      new: { top: 0, left: 0 },
    },
    mappingDebugSignature: "",
    lineMappingDebugSignature: "",
    mappingDebugAnchorCount: 0,
    profileDraft: createDefaultProfile(),
  };
}
